name: hello-world
on: 
  push:
    branches: [main]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV  
      - run: echo Hello World, today is $TODAY
  build:
    runs-on: ubuntu-latest
    steps:
      # Bước 1: Checkout mã nguồn từ repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Docker registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bước 3: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest .

      # Bước 4: Push Docker image lên Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest